server:
  port: 8180
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: prod
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    enabled: true
    content-type: text/html
  http:
    encoding:
      force: true
  application:
    name: wx